name: CICD_Workflow_1
on:
  workflow_dispatch:
  push:
    branches: [main]
env:
  APP_NAME: register-app-pipeline
  RELEASE: 1.0.0
  SONAR_TOKEN: ${{secrets.SONARQUBE_TOKEN}}
  SONARQUBE_SERVER: ${{secrets.SONARQUBE_SERVER}}

jobs:
  CODE_CHECKOUT:
    runs-on: self-hosted
    steps:
      - name: clean-up workspace
        run: |
          rm -rf * .[^.]*
          echo "✓ Workspace cleaned"

      - name: Code Checkout
        uses: actions/checkout@v4

  TOOLS_INSTALLATION_VERIFICATION:
    runs-on: self-hosted
    needs: CODE_CHECKOUT
    steps:
      - name: checking java version
        run: java --version    
    
      - name: checking Maven version
        run: mvn --version

  BUILD_APPLICATION:
    needs: TOOLS_INSTALLATION_VERIFICATION
    runs-on: self-hosted
    steps:
      - name: Cleaning and package Installing
        run: mvn clean package      

  Verify_Compilation:
    needs: BUILD_APPLICATION
    runs-on: self-hosted
    steps:
      - name: Listing compiled class files in target/classes
        run: find target/classes -name "*.class" || echo "No .class files found!"

  SONAR_SCAN:
    needs: Verify_Compilation
    runs-on: self-hosted
    steps:

      - name: Run Sonar Analysis
        run: |
          echo $PATH
          which sonar-scanner || true
          ls -l /opt/sonar-scanner/bin

          /opt/sonar-scanner/bin/sonar-scanner --version

           mvn clean verify sonar:sonar \
          -Dsonar.projectKey=game-app_ga-1 \
          -Dsonar.token=${{env.SONAR_TOKEN}} \
          -Dsonar.host.url=${{env.SONARQUBE_SERVER}}        

  DOCKER_IMAGE_BUILD_AND_PUSH:
    needs: SONAR_SCAN
    runs-on: self-hosted
    steps:
      - name: Building the Image 
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE }}-${{ github.run_number }} .

      - name: SUDO Docker Image
        run: docker images  

      - name: DockerHub Login
        uses: docker/login-action@v4
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Image Push To Registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE }}-${{ github.run_number }}

  TRIVY_SCANNING:
    needs: DOCKER_IMAGE_BUILD_AND_PUSH
    runs-on: self-hosted
    steps:
      - name: Mounting the Docker Deamon in the Trivy Conatiner and Pulling and Scanning the docker image
        run: | 
          docker run -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE }}-${{ github.run_number }} \
          --no-progress --scanners vuln --exit-code 0 --severity HIGH,CRITICAL --format table

  HOSTING_THE_APPLICATION_TO_THE_SERVER:
    needs: TRIVY_SCANNING
    runs-on: self-hosted
    steps:
      - name: Host the application to the server 
        run: |
          docker run -d -p 8082:8080 --name test-app ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE }}-${{ github.run_number }} 
      - name: wait period
        run: sleep 30

  DAST_SCAN:
    needs: HOSTING_THE_APPLICATION_TO_THE_SERVER
    runs-on: self-hosted
    steps:
      - name: OWASP ZAP Security Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw \
          -t owasp/zap2docker-stable zap-baseline.py \
          -t http://65.2.121.174:8082/ \
          -r zap-report.html || true
           echo "✓ ZAP scan completed"

      - name: uplaod ZAP report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html


  VIEW_ZAP_REPORT:
    needs: DAST_SCAN
    runs-on: self-hosted
    steps:
      - name: Download ZAP artifact
        uses: actions/download-artifact@v4
        with:
          name: zap-report

      - name: View ZAP report
        run: ls -lh zap-report.html

  CLEANUP_ARTIFACT:
    needs: VIEW_ZAP_REPORT
    runs-on: self-hosted
    steps:
      - name: Deleing the Docker images
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.RELEASE }}-${{ github.run_number }} || true                

  POST_ACTIVITY:
    needs: CLEANUP_ARTIFACT
    runs-on: self-hosted
    if: always()
    steps:
      
      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "${{github.workflow}} - Build ${{github.run_number}} Successful"
          to: kabir647474@gmail.com
          from: CI Pipeline
          body: |
            Build Successful 

            Workflow: ${{ github.workflow }}
            Run Number: ${{ github.run_number }}
            Repo: ${{ github.repository }}

            View Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}                     